name: integration continuos

on: 
  push:
    branches: [develop]

jobs: 
  ci_to_develop:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run test
      - run: npm run build