name: integration continuos

on: 
  pull_request:
    branches: [testing]

jobs: 
  ci_to_develop:
    runs-on: windows-server
    steps:
      - uses: actions/checkout@v2
      - run: npm run test
      - run: npm run build